-- ═══════════════════════════════════════════════════════════════════
--  Seed de desarrollo
--
--  Los perfiles y usuarios de auth se crean con seed-auth.sh,
--  que debe ejecutarse DESPUÉS del db reset porque los perfiles
--  tienen FK a auth.users (que GoTrue crea con su propia API).
--
--  Ejecutar después del reset:
--    bash supabase/seed-auth.sh
-- ═══════════════════════════════════════════════════════════════════

-- (vacío intencionalmente — ver seed-auth.sh)
